backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "data/pages/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Hero Slides"
            name: "slides"
            widget: "list"
            fields:
              - {label: "Slide Title", name: "title", widget: "string"}
              - {label: "Slide Subheadline", name: "subhead", widget: "text"}
              - {label: "Background Image", name: "image", widget: "image"}
              - {label: "Button Link", name: "link", widget: "string", required: false}
          - label: "Industry Expertise Section"
            name: "industries"
            widget: "list"
            fields:
              - {label: "Industry Name", name: "name", widget: "string"}
              - {label: "Industry Description", name: "desc", widget: "text"}
              
  - name: "database"
    label: "Publishing"
    files:
      - file: "data/signals.json"
        label: "Market Signals Database"
        name: "signals"
        fields:
          - label: "All Market Signals"
            name: "articles"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime"}
              - {label: "Summary", name: "summary", widget: "text"}
              - {label: "Full Story", name: "body", widget: "markdown"}
